CREATE DATABASE storage_inventory;

USE storage_inventory;

CREATE TABLE USER(
    ID int primary key auto_increment,
    USERNAME varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE enum('ADMIN', 'WORKER', 'USER') NOT NULL
);

CREATE TABLE CATEGORY(
    ID int primary key auto_increment,
    CATEGORY varchar(255) NOT NULL
);

CREATE TABLE SHELF(
    ID int primary key auto_increment,
    SHELFNAME varchar(255) NOT NULL
);

CREATE TABLE PRODUCTS(
    ID int primary key auto_increment,
    PRODUCTNAME varchar(255) NOT NULL,
    CATEGORY_ID int NOT NULL,
    PRICE int NOT NULL,
    SUPPLIER varchar(255) NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE INVENTORY(
    ID int primary key auto_increment,
    SHELF_ID int NOT NULL,
    PRODUCT_ID int NOT NULL,
    QUANTITY int NOT NULL,
    LASTUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SHELF_ID) REFERENCES SHELF(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE LOGS(
    ID int primary key auto_increment,
    USER_ID int NOT NULL,
    TARGET_ID int NOT NULL,
    TARGET_TYPE varchar(255) NOT NULL,
    DESCRIPTION varchar(255) NOT NULL,
    ACTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);